/* global __dirname */

import fs from 'node:fs';
import path from 'node:path';

import webpack from 'webpack';
import runner from '@babel/helper-plugin-test-runner';

import { localIdentNameFactory } from '../src/utils';

/**
 * Creates Webpack compiler instance, providing it with all configs we need
 * in our tests, beside a few customizeable options.
 * @param {object} ops Options.
 * @param {string} ops.entry Webpack's entry points.
 * @param {object} ops.cssGeneratorOps Options of CSS module generator.
 * @returns {object} Webpack compiler.
 */
function newWebpackCompiler({ cssGeneratorOps, entry }) {
  const compiler = webpack({
    context: path.resolve(__dirname, '..'),
    entry,
    experiments: { css: true },
    mode: 'production',
    module: {
      generator: {
        'css/module': cssGeneratorOps,
      },
      rules: [{
        test: /\.css$/u,
        type: 'css/module',
      }],
    },
  });
  compiler.hooks.shouldEmit.tap('Test', () => false);
  return compiler;
}

/**
 * Runs a Webpack-base test:
 *  - It runs Webpack compilation of the CSS file specified by `entry` option,
 *    using other Webpack-related options passed into this function.
 *  - It extracts classnames from the Webpack-generated CSS bundle.
 *  - It compares that each classname generated by Webpack is present
 *    in the Babel compilation output, pointed by `babelOutput`.
 * @param {object} ops Options.
 * @param {string} ops.babelOutput Babel output file to use, relative to
 *  the fixtures folder.
 * @param {object} ops.cssGeneratorOps Options of CSS module generator.
 * @param {string} ops.entry Webpack's entry points, relative to
 *  the fixtures folder.
 * @returns {object} Webpack compiler.
 */
function runWebpackTest({ babelOutput, cssGeneratorOps, entry }) {
  return new Promise((resolve, reject) => {
    const compiler = newWebpackCompiler({
      cssGeneratorOps,
      entry: `./test/fixtures/${entry}`,
    });
    compiler.run((error, stats) => {
      try {
        // Extracts compiled CSS from the Webpack compilation stats.
        const cssChunkName = Object.keys(stats.compilation.assets)
          .find((key) => key.endsWith('.css'));

        /* eslint-disable no-underscore-dangle */
        let asset = stats.compilation.assets[cssChunkName];
        if (asset._source) asset = asset._source;

        const compiledCss = asset._valueAsString;
        const classNames = compiledCss.match(/\.[^{]*/gu);
        /* eslint-enable no-underscore-dangle */

        // Gets outputs of Babel compilation, and checks that they contain
        // each classname generated by Webpack.
        const babelOutputJs = fs.readFileSync(
          `${__dirname}/fixtures/${babelOutput}`,
          'utf8',
        );
        for (let i = 0; i < classNames.length; ++i) {
          let name = classNames[i];

          // NOTE: This unescapes CSS class name, it is to be doulbe-checked
          // though, whether it is fine we inject unescaped names into className
          // prop, or should we escape that.
          name = name.replace(/\\(.)/g, '$1');

          if (!babelOutputJs.includes(`"${name.slice(1)}"`)) {
            throw Error(
              `Babel output:\n\n${babelOutputJs}\n\nMisses class: ${name}`,
            );
          }
        }
        resolve();
      } catch (e) {
        reject(e);
      }
    });
  });
}

// Runs Babel on test cases inside ./fixtures folder,
// using @babel/helper-plugin-test-runner, and verifies
// that outputs match expected values.
runner(import.meta.url);

// These are Webpack-based tests, comparing that outputs of Babel compilation
// match results of Webpack CSS processing.
describe('Webpack compatibility', () => {
  it(
    'compatible with `localIdentName` string',
    () => runWebpackTest({
      babelOutput: 'webpack_compatibility/generated_hashes/output.mjs',
      cssGeneratorOps: {
        localIdentName: '[path]__[local]__[hash:base64:5]',
      },
      entry: 'webpack_compatibility/generated_hashes/style.css',
    }),
  );

  it(
    'compatible with the "stable" `localIdentName` function',
    () => runWebpackTest({
      babelOutput: 'webpack_compatibility/stable_classnames/output.mjs',
      cssGeneratorOps: {
        localIdentName: localIdentNameFactory(
          '[path]__[local]__[hash:base64:5]',
        ),
      },
      entry: 'webpack_compatibility/stable_classnames/style.css',
    }),
  );
});
