version: 2
jobs:
  test-node-14:
    docker:
      - image: cimg/node:14.21
    steps:
      - checkout
      - restore_cache:
          key: node-modules-14-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-14-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  test-node-16:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - restore_cache:
          key: node-modules-16-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-16-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  test-node-18:
    docker:
      - image: cimg/node:18.15 # LTS
    steps:
      - checkout
      - restore_cache:
          key: node-modules-18-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-18-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  test-node-19:
    docker:
      - image: cimg/node:19.8
    steps:
      - checkout
      - restore_cache:
          key: node-modules-19-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-19-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
  release:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: node-modules-lts-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-lts-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --access public

test-filters: &test-filters
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - test-node-14:
          <<: *test-filters
      - test-node-16:
          <<: *test-filters
      - test-node-18:
          <<: *test-filters
      - test-node-19:
          <<: *test-filters
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-rc\.\d+)?/
          requires:
            - test-node-14
            - test-node-16
            - test-node-18
            - test-node-19
